apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cloudsqlproxy-0-6
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/cloudsqlproxy-0-6@sha256:edda7f2eea514b9d3b199e1ab05b86a514f1539a1984c6b5e2f5becf0c363949
        name: my-go
        resources: {}
status: {}
