apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cloudsqlproxy-0-6
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/cloudsqlproxy-0-6@sha256:e5d07816e981d0976c698b5a614c46171dbdb159f8f70064dd227f4347f3b9f0
        name: my-go
        resources: {}
status: {}
