apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: trillian-logsigner-1-5
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/trillian-logsigner-1-5@sha256:8ade6afc4a2a7bed7127b746c85da2e9f1fbdc5150056e04e59e1800057e3c2b
        name: my-go
        resources: {}
status: {}
