apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: trillian-logsigner-1-5
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/trillian-logsigner-1-5@sha256:015f430f8f966d5cf83cdaad5ba5ca87dd75a83e64abd229c00ddd370f3c393b
        name: my-go
        resources: {}
status: {}
