apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: createtree-0-6
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/createtree-0-6@sha256:0293750aba7731b356cbcea6c352b296a118d58289455a7d9869d53ad34b47b3
        name: my-go
        resources: {}
status: {}
