apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: createtree-0-6
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/createtree-0-6@sha256:2dec70974ce8657a08705b76e7dd2d7131d92c5b1535d7d04e7b0dddc01d7a30
        name: my-go
        resources: {}
status: {}
