apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: createtree-0-6
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/createtree-0-6@sha256:458ea3a2516134a4fe83ac5828fb2de648af53b35c991189c556b0d117b0f082
        name: my-go
        resources: {}
status: {}
