apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: createtree-0-6
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/createtree-0-6@sha256:317d910904719d2d8b7ae37a1b140eef6994edc20ac1567a7c45df4ba9948ca7
        name: my-go
        resources: {}
status: {}
