apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: createtree-0-6
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/createtree-0-6@sha256:43fb0fc43e3f663b799336275d9367cb999f2c82311dfccaa6ab75ef1e254180
        name: my-go
        resources: {}
status: {}
