apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: trillian-database-1-5
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/trillian-database-1-5@sha256:6255874c30bda2314bc383d1c24c3e284f1f7ec400dbcafc264e63b1cc7d686f
        name: my-go
        resources: {}
status: {}
