apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: redis-0-6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: redis-0-6
    app.kubernetes.io/part-of: trillian-1-0-gamma
  name: redis-0-6
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    app.kubernetes.io/instance: redis-0-6
status:
  loadBalancer: {}
