apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: redis-0-6
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/redis-0-6@sha256:be343cb799d09978fc51aa6041ecedb5b7e852d696544a17c29e105b76d2e4ae
        name: my-go
        resources: {}
status: {}
