apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: redis-0-6
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/redis-0-6@sha256:8aa7e22774aed9ea45e63c2ea83664051c10a46d3456966a8245f1d50cf53c88
        name: my-go
        resources: {}
status: {}
