apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: redis-0-6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: redis-0-6
    app.kubernetes.io/part-of: trillian-1-0-gamma
  name: redis-0-6oplb
spec:
  path: /
  port:
    targetPort: 6379
  to:
    kind: Service
    name: redis-0-6
    weight: null
status: {}
