apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cloudsqlproxy-0-6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cloudsqlproxy-0-6
    app.kubernetes.io/part-of: trillian-1-0-gamma
  name: cloudsqlproxy-0-6
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: cloudsqlproxy-0-6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: cloudsqlproxy-0-6
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/cloudsqlproxy-0-6@sha256:9565d99fdf9dceabdec95d0d64bb98571e4a59beb3ecf6fc07d3e550e5680691
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
