apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: trillian-netcat-1-5
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/trillian-netcat-1-5@sha256:d843f5be29ede4c950d807028ce0829223f53c2ec43a747bc11ae1e4dc2dbf5d
        name: my-go
        resources: {}
status: {}
