apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: trillian-netcat-1-5
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/trillian-netcat-1-5@sha256:22b3d38783d2ec51a2898ee54aed562d9e71f54fd6098c8bf85f303ebfd4c283
        name: my-go
        resources: {}
status: {}
