apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: trillian-netcat-1-5
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/trillian-netcat-1-5@sha256:7b00e13c1b050d4ffec402ed1bac24090b3dff8477f87df8291bc09a9851c32c
        name: my-go
        resources: {}
status: {}
