apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: trillian-netcat-1-5
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/trillian-netcat-1-5@sha256:c876c793f3fb23958e6b381c302b86133ebf2ea49a6153c8a2014ab8a24a4929
        name: my-go
        resources: {}
status: {}
