apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: trillian-logserver-1-5
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/trillian-logserver-1-5@sha256:d6bebd674b5d66bb742bf96dbbea761e2fa73a9fabd9be8a48cefbfc906e990c
        name: my-go
        resources: {}
status: {}
