apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: trillian-logserver-1-5
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/trillian-logserver-1-5@sha256:9a4360d1327565f9cc7f7d96b9c7a0ab269488961960d7226118aff544310214
        name: my-go
        resources: {}
status: {}
