apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: trillian-logserver-1-5
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/trillian-logserver-1-5@sha256:e1ec119c4caadecb80359edb4c06c2558c9dedcb965203f5d56277ff297d90f1
        name: my-go
        resources: {}
status: {}
