apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: trillian-logserver-1-5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: trillian-logserver-1-5
    app.kubernetes.io/part-of: trillian-1-0-gamma
  name: trillian-logserver-1-5
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: trillian-logserver-1-5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: trillian-logserver-1-5
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/trillian-logserver-1-5@sha256:56a3a063e5e0729a0bb72eb3f4233b00cb0f4fee22c1df3f01e406b52824ed41
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 6379
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
