apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: createdb-0-6
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/createdb-0-6@sha256:673ba28f779c1141aa85c07f2585faa98a76810fb41dac6d5cdc4f2407608e89
        name: my-go
        resources: {}
status: {}
